### Step 1: Mount the Google Drive

Remember to use GPU runtime before mounting your Google Drive. (Runtime --> Change runtime type).

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Step 2: Open the project directory

Replace `Your_Dir` with your own path.

In [2]:
cd /content/drive/MyDrive/ECE_C247A_Final_Project/

/content/drive/MyDrive/ECE_C247A_Final_Project

### Step 3: Install required packages

After installing them, Colab will require you to restart the session.

In [3]:
!pip install -r requirements.txt

Collecting https://github.com/kpu/kenlm/archive/master.zip (from -r requirements.txt (line 31))
  Downloading https://github.com/kpu/kenlm/archive/master.zip
     - 553.6 kB 582.4 kB/s 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click==8.1.7 (from -r requirements.txt (line 1))
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting datasets==2.19.2 (from -r requirements.txt (line 2))
  Downloading datasets-2.19.2-py3-none-any.whl.metadata (19 kB)
Collecting h5py==3.11.0 (from -r requirements.txt (line 3))
  Downloading h5py-3.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting hydra-core==1.3.2 (from -r requirements.txt (line 4))
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting hydra-submitit-launcher==1.2.0 (from -r requirements.txt (line 5))
  Downloading hydra_submitit_launcher-1.2.0-py3-none-any.whl.metadata (1.1 kB)
Collecting hypothesis==6.97.6 (from -r requirements.txt (line 6))
  Downloading hypothesis-6.97.6-py3-none-any.whl.metadata (6.0 kB)
Collecting lightning-bolts==0.7.0 (from -r requirements.txt (line 7))
  Downloading lightning_bolts-0.7.0-py3-none-any.whl.metadata (9.5 kB)
Collecting mne-bids==0.15.0 (from -r requirements.txt (line 8))
  Downloading mne_bids-0.15.0-py3-none-any.whl.metadata (7.2 kB)
Collecting nltk==3.8.1 (from -r requirements.txt (line 9))
  Downloading nltk-3.8.1-py3-none-any.whl.metadata (2.8 kB)
Collecting numpy==1.26.4 (from -r requirements.txt (line 10))
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 6.8 MB/s eta 0:00:00
Requirement already satisfied: omegaconf==2.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 11)) (2.3.0)
Requirement already satisfied: pandas==2.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 12)) (2.2.2)
Collecting pip==24.0 (from -r requirements.txt (line 13))
  Downloading pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Collecting pre-commit==3.7.1 (from -r requirements.txt (line 14))
  Downloading pre_commit-3.7.1-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting pytest-benchmark==4.0.0 (from -r requirements.txt (line 15))
  Downloading pytest_benchmark-4.0.0-py3-none-any.whl.metadata (23 kB)
Collecting pytest-cov==5.0.0 (from -r requirements.txt (line 16))
  Downloading pytest_cov-5.0.0-py3-none-any.whl.metadata (27 kB)
Collecting pytest-env==1.1.3 (from -r requirements.txt (line 17))
  Downloading pytest_env-1.1.3-py3-none-any.whl.metadata (5.3 kB)
Collecting pytest-mock==3.14.0 (from -r requirements.txt (line 18))
  Downloading pytest_mock-3.14.0-py3-none-any.whl.metadata (3.8 kB)
Collecting pytest-rerunfailures==14.0 (from -r requirements.txt (line 19))
  Downloading pytest_rerunfailures-14.0-py3-none-any.whl.metadata (18 kB)
Collecting pytest-xdist==3.5.0 (from pytest-xdist[psutil]==3.5.0->-r requirements.txt (line 20))
  Downloading pytest_xdist-3.5.0-py3-none-any.whl.metadata (3.1 kB)
Collecting pytest==7.4.4 (from -r requirements.txt (line 21))
  Downloading pytest-7.4.4-py3-none-any.whl.metadata (7.9 kB)
Collecting python-levenshtein>=0.25.0 (from -r requirements.txt (line 22))
  Downloading python_levenshtein-0.27.3-py3-none-any.whl.metadata (3.9 kB)
Collecting pytorch-lightning==1.8.6 (from -r requirements.txt (line 23))
  Downloading pytorch_lightning-1.8.6-py3-none-any.whl.metadata (23 kB)
Collecting torch==2.3.0 (from -r requirements.txt (line 24))
  Downloading torch-2.3.0-cp312-cp312-manylinux1_x86_64.whl.metadata (26 kB)
Collecting scipy==1.13.1 (from -r requirements.txt (line 25))
  Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 7.2 MB/s eta 0:00:00
Collecting setuptools==69.5.1 (from -r requirements.txt (line 26))
  Downloading setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
Collecting torchaudio==2.3.0 (from -r requirements.txt (line 27))
  Downloading torchaudio-2.3.0-cp312-cp312-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting torchmetrics==0.11.4 (from -r requirements.txt (line 28))
  Downloading torchmetrics-0.11.4-py3-none-any.whl.metadata (15 kB)
Collecting trio==0.23.2 (from -r requirements.txt (line 29))
  Downloading trio-0.23.2-py3-none-any.whl.metadata (4.9 kB)
Collecting unidecode==1.3.8 (from -r requirements.txt (line 30))
  Downloading Unidecode-1.3.8-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.2->-r requirements.txt (line 2)) (3.25.1)
Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.2->-r requirements.txt (line 2)) (18.1.0)
Collecting pyarrow-hotfix (from datasets==2.19.2->-r requirements.txt (line 2))
  Downloading pyarrow_hotfix-0.7-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.2->-r requirements.txt (line 2)) (0.3.8)
Requirement already satisfied: requests>=2.32.1 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.2->-r requirements.txt (line 2)) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.2->-r requirements.txt (line 2)) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.2->-r requirements.txt (line 2)) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.2->-r requirements.txt (line 2)) (0.70.16)
Collecting fsspec<=2024.3.1,>=2023.1.0 (from fsspec[http]<=2024.3.1,>=2023.1.0->datasets==2.19.2->-r requirements.txt (line 2))
  Downloading fsspec-2024.3.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.2->-r requirements.txt (line 2)) (3.13.3)
Requirement already satisfied: huggingface-hub>=0.21.2 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.2->-r requirements.txt (line 2)) (1.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.2->-r requirements.txt (line 2)) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.2->-r requirements.txt (line 2)) (6.0.3)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core==1.3.2->-r requirements.txt (line 4)) (4.9.3)
Collecting submitit>=1.3.3 (from hydra-submitit-launcher==1.2.0->-r requirements.txt (line 5))
  Downloading submitit-1.5.4-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from hypothesis==6.97.6->-r requirements.txt (line 6)) (25.4.0)
Requirement already satisfied: sortedcontainers<3.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from hypothesis==6.97.6->-r requirements.txt (line 6)) (2.4.0)
Collecting lightning-utilities>0.3.1 (from lightning-bolts==0.7.0->-r requirements.txt (line 7))
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: torchvision>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from lightning-bolts==0.7.0->-r requirements.txt (line 7)) (0.25.0+cu128)
Requirement already satisfied: tensorboard>=2.9.1 in /usr/local/lib/python3.12/dist-packages (from lightning-bolts==0.7.0->-r requirements.txt (line 7)) (2.19.0)
Collecting mne>=1.5 (from mne-bids==0.15.0->-r requirements.txt (line 8))
  Downloading mne-1.11.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk==3.8.1->-r requirements.txt (line 9)) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk==3.8.1->-r requirements.txt (line 9)) (2025.11.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2->-r requirements.txt (line 12)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2->-r requirements.txt (line 12)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2->-r requirements.txt (line 12)) (2025.3)
Collecting cfgv>=2.0.0 (from pre-commit==3.7.1->-r requirements.txt (line 14))
  Downloading cfgv-3.5.0-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting identify>=1.0.0 (from pre-commit==3.7.1->-r requirements.txt (line 14))
  Downloading identify-2.6.17-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting nodeenv>=0.11.1 (from pre-commit==3.7.1->-r requirements.txt (line 14))
  Downloading nodeenv-1.10.0-py2.py3-none-any.whl.metadata (24 kB)
Collecting virtualenv>=20.10.0 (from pre-commit==3.7.1->-r requirements.txt (line 14))
  Downloading virtualenv-21.2.0-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from pytest-benchmark==4.0.0->-r requirements.txt (line 15)) (9.0.0)
Collecting coverage>=5.2.1 (from coverage[toml]>=5.2.1->pytest-cov==5.0.0->-r requirements.txt (line 16))
  Downloading coverage-7.13.4-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (8.5 kB)
Collecting execnet>=1.1 (from pytest-xdist==3.5.0->pytest-xdist[psutil]==3.5.0->-r requirements.txt (line 20))
  Downloading execnet-2.1.2-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.12/dist-packages (from pytest==7.4.4->-r requirements.txt (line 21)) (2.3.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from pytest==7.4.4->-r requirements.txt (line 21)) (1.6.0)
Collecting tensorboardX>=2.2 (from pytorch-lightning==1.8.6->-r requirements.txt (line 23))
  Downloading tensorboardx-2.6.4-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning==1.8.6->-r requirements.txt (line 23)) (4.15.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from torch==2.3.0->-r requirements.txt (line 24)) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch==2.3.0->-r requirements.txt (line 24)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.0->-r requirements.txt (line 24)) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.3.0->-r requirements.txt (line 24))
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.3.0->-r requirements.txt (line 24))
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.3.0->-r requirements.txt (line 24))
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.3.0->-r requirements.txt (line 24))
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.3.0->-r requirements.txt (line 24))
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.3.0->-r requirements.txt (line 24))
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.3.0->-r requirements.txt (line 24))
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.3.0->-r requirements.txt (line 24))
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.3.0->-r requirements.txt (line 24))
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch==2.3.0->-r requirements.txt (line 24))
  Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.3.0->-r requirements.txt (line 24))
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio==0.23.2->-r requirements.txt (line 29)) (3.11)
Collecting outcome (from trio==0.23.2->-r requirements.txt (line 29))
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio==0.23.2->-r requirements.txt (line 29)) (1.3.1)
Requirement already satisfied: psutil>=3.0 in /usr/local/lib/python3.12/dist-packages (from pytest-xdist[psutil]==3.5.0->-r requirements.txt (line 20)) (5.9.5)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.3.0->-r requirements.txt (line 24)) (12.8.93)
Collecting Levenshtein==0.27.3 (from python-levenshtein>=0.25.0->-r requirements.txt (line 22))
  Downloading levenshtein-0.27.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting rapidfuzz<4.0.0,>=3.9.0 (from Levenshtein==0.27.3->python-levenshtein>=0.25.0->-r requirements.txt (line 22))
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.2->-r requirements.txt (line 2)) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.2->-r requirements.txt (line 2)) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.2->-r requirements.txt (line 2)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.2->-r requirements.txt (line 2)) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.2->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.2->-r requirements.txt (line 2)) (1.23.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.21.2->datasets==2.19.2->-r requirements.txt (line 2)) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.21.2->datasets==2.19.2->-r requirements.txt (line 2)) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.21.2->datasets==2.19.2->-r requirements.txt (line 2)) (0.24.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from mne>=1.5->mne-bids==0.15.0->-r requirements.txt (line 8)) (4.4.2)
Requirement already satisfied: lazy-loader>=0.3 in /usr/local/lib/python3.12/dist-packages (from mne>=1.5->mne-bids==0.15.0->-r requirements.txt (line 8)) (0.5)
Requirement already satisfied: matplotlib>=3.8 in /usr/local/lib/python3.12/dist-packages (from mne>=1.5->mne-bids==0.15.0->-r requirements.txt (line 8)) (3.10.0)
Requirement already satisfied: pooch>=1.5 in /usr/local/lib/python3.12/dist-packages (from mne>=1.5->mne-bids==0.15.0->-r requirements.txt (line 8)) (1.9.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2->-r requirements.txt (line 12)) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.1->datasets==2.19.2->-r requirements.txt (line 2)) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.1->datasets==2.19.2->-r requirements.txt (line 2)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.1->datasets==2.19.2->-r requirements.txt (line 2)) (2026.2.25)
Requirement already satisfied: cloudpickle>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from submitit>=1.3.3->hydra-submitit-launcher==1.2.0->-r requirements.txt (line 5)) (3.1.2)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.9.1->lightning-bolts==0.7.0->-r requirements.txt (line 7)) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.9.1->lightning-bolts==0.7.0->-r requirements.txt (line 7)) (1.78.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.9.1->lightning-bolts==0.7.0->-r requirements.txt (line 7)) (3.10.2)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.9.1->lightning-bolts==0.7.0->-r requirements.txt (line 7)) (5.29.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.9.1->lightning-bolts==0.7.0->-r requirements.txt (line 7)) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.9.1->lightning-bolts==0.7.0->-r requirements.txt (line 7)) (3.1.6)
INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
Collecting torchvision>=0.10.0 (from lightning-bolts==0.7.0->-r requirements.txt (line 7))
  Downloading torchvision-0.25.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.4 kB)
  Downloading torchvision-0.24.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
  Downloading torchvision-0.24.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
  Downloading torchvision-0.23.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
  Downloading torchvision-0.22.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
  Downloading torchvision-0.22.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
  Downloading torchvision-0.21.0-cp312-cp312-manylinux1_x86_64.whl.metadata (6.1 kB)
INFO: pip is still looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
  Downloading torchvision-0.20.1-cp312-cp312-manylinux1_x86_64.whl.metadata (6.1 kB)
  Downloading torchvision-0.20.0-cp312-cp312-manylinux1_x86_64.whl.metadata (6.1 kB)
  Downloading torchvision-0.19.1-cp312-cp312-manylinux1_x86_64.whl.metadata (6.0 kB)
  Downloading torchvision-0.19.0-cp312-cp312-manylinux1_x86_64.whl.metadata (6.0 kB)
  Downloading torchvision-0.18.1-cp312-cp312-manylinux1_x86_64.whl.metadata (6.6 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.

### Step 4: Start your experiments!

- Remember to download and copy the dataset to this directory: `Your_Dir/emg2qwerty/data`.
- You may now start your experiments with any scripts! Below are examples of single-user training and testing (greedy decoding).
- **There are two ways to track the logs:**
  - 1. Keep `--multirun`, and the logs will not be printed here, but they will be saved in the folder `logs`, e.g., `logs/2025-02-09/18-24-15/submitit_logs/`.
  - 2. Comment out `--multirun` and the logs will be printed in this notebook, but they will not be saved.

#### Training

- The checkpoints are saved in the folder `logs`, e.g., `logs/2025-02-09/18-24-15/checkpoints/`.

In [ ]:
import subprocess
from pathlib import Path
import pandas as pd
import re

repo_dir = Path("/content/drive/MyDrive/ECE_C247A_Final_Project")

channel_sets = {
    16: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    12: [0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14],
    8:  [0, 2, 4, 6, 8, 10, 12, 14],
    4:  [0, 4, 8, 12],
}

results = []

def parse_float_from_line(line: str):
    matches = re.findall(r"[-+]?\d*\.\d+|\d+", line)
    return float(matches[-1]) if matches else None

for n_channels, channels in channel_sets.items():
    in_features = n_channels * 33

    print(f"\n{'='*60}")
    print(f"Running experiment with {n_channels} channels")
    print(f"Selected channels: {channels}")
    print(f"in_features: {in_features}")
    print(f"{'='*60}\n")

    cmd = [
        "python", "-u", "-m", "emg2qwerty.train",
        "user=single_user",
        "trainer.accelerator=gpu",
        "trainer.devices=1",
        "trainer.max_epochs=50",
        "num_workers=2",
        "module.lstm_hidden_size=256",
        "module.lstm_num_layers=2",
        "module.lstm_dropout=0.2",
        "optimizer.lr=0.0005",
        f"module.electrode_channels={n_channels}",
        f"module.in_features={in_features}",
        f"module.selected_channels={channels}",
    ]

    best_val_cer = None
    final_val_cer = None
    final_test_cer = None

    process = subprocess.Popen(
        cmd,
        cwd=repo_dir,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )

    for line in process.stdout:
        print(line, end="")

        if "'val/CER' reached" in line:
            try:
                cer_str = line.split("reached")[1].split("(")[0].strip()
                best_val_cer = float(cer_str)
            except:
                pass

        if "│          val/CER" in line:
            val = parse_float_from_line(line)
            if val is not None:
                final_val_cer = val

        if "│         test/CER" in line:
            val = parse_float_from_line(line)
            if val is not None:
                final_test_cer = val

    return_code = process.wait()

    if return_code != 0:
        print(f"\nRun failed for {n_channels} channels\n")
        results.append({
            "channels": n_channels,
            "selected_channels": channels,
            "in_features": in_features,
            "best_val_CER": None,
            "final_val_CER": None,
            "final_test_CER": None,
        })
    else:
        results.append({
            "channels": n_channels,
            "selected_channels": channels,
            "in_features": in_features,
            "best_val_CER": best_val_cer,
            "final_val_CER": final_val_cer,
            "final_test_CER": final_test_cer,
        })

    results_df = pd.DataFrame(results).sort_values("channels", ascending=False)
    display(results_df)

results_df = pd.DataFrame(results).sort_values("channels", ascending=False)
results_df.to_csv(repo_dir / "channel_ablation_results.csv", index=False)

print("\nSaved summary to:")
print(repo_dir / "channel_ablation_results.csv")
display(results_df)

============================================================
Running experiment with 16 channels
Selected channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
in_features: 528
============================================================

[2026-03-12 09:23:06,817][__main__][INFO] -
Config:
user: single_user
dataset:
  train:
  - user: 89335547
    session: 2021-06-03-1622765527-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-02-1622681518-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-04-1622863166-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627003020-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-21-1626916256-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627004019-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622885888-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-02-1622679967-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-03-1622764398-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-21-1626917264-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622889105-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-03-1622766673-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-04-1622861066-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627001995-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622884635-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-21-1626915176-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  val:
  - user: 89335547
    session: 2021-06-04-1622862148-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  test:
  - user: 89335547
    session: 2021-06-02-1622682789-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  root: ${hydra:runtime.cwd}/data
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields:
  - emg_left
  - emg_right
band_rotation:
  _target_: emg2qwerty.transforms.ForEach
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets:
    - -1
    - 0
    - 1
temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120
logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16
specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 25
  n_freq_masks: 2
  freq_mask_param: 4
transforms:
  train:
  - ${to_tensor}
  - ${band_rotation}
  - ${temporal_jitter}
  - ${logspec}
  - ${specaug}
  val:
  - ${to_tensor}
  - ${logspec}
  test: ${transforms.val}
module:
  _target_: emg2qwerty.lightning.TDSConvLSTMCTCModule
  in_features: 528
  mlp_features:
  - 384
  block_channels:
  - 24
  - 24
  - 24
  kernel_width: 32
  lstm_hidden_size: 256
  lstm_num_layers: 2
  lstm_dropout: 0.2
  electrode_channels: 16
  selected_channels:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding:
  - 1800
  - 200
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0005
lr_scheduler:
  scheduler:
    _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
    warmup_epochs: 10
    max_epochs: ${trainer.max_epochs}
    warmup_start_lr: 1.0e-08
    eta_min: 1.0e-06
  interval: epoch
decoder:
  _target_: emg2qwerty.decoder.CTCGreedyDecoder
seed: 1501
batch_size: 32
num_workers: 2
train: true
checkpoint: null
monitor_metric: val/CER
monitor_mode: min
trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 50
  default_root_dir: ${hydra:runtime.output_dir}
callbacks:
- _target_: pytorch_lightning.callbacks.LearningRateMonitor
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${hydra:runtime.output_dir}/checkpoints
  monitor: ${monitor_metric}
  mode: ${monitor_mode}
  save_last: true
  verbose: true

Global seed set to 1501
[2026-03-12 09:23:06,822][__main__][INFO] - Instantiating LightningModule {'_target_': 'emg2qwerty.lightning.TDSConvLSTMCTCModule', 'in_features': 528, 'mlp_features': [384], 'block_channels': [24, 24, 24], 'kernel_width': 32, 'lstm_hidden_size': 256, 'lstm_num_layers': 2, 'lstm_dropout': 0.2, 'electrode_channels': 16, 'selected_channels': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]}
Num LSTM layers:  2
Layer size:  256
[2026-03-12 09:23:06,970][__main__][INFO] - Instantiating LightningDataModule {'_target_': 'emg2qwerty.lightning.WindowedEMGDataModule', 'window_length': 8000, 'padding': [1800, 200]}
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: /content/drive/MyDrive/ECE_C247A_Final_Project/logs/2026-03-12/09-23-06/lightning_logs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/usr/local/lib/python3.12/dist-packages/pl_bolts/__init__.py:11: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(numpy, tp_name):
/usr/local/lib/python3.12/dist-packages/pl_bolts/__init__.py:11: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  if not hasattr(numpy, tp_name):
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:34: UnderReviewWarning: The feature generate_power_seq is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  "lr_options": generate_power_seq(LEARNING_RATE_CIFAR, 11),
/usr/local/lib/python3.12/dist-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:92: UnderReviewWarning: The feature FeatureMapContrastiveTask is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  contrastive_task: Union[FeatureMapContrastiveTask] = FeatureMapContrastiveTask("01, 02, 11"),
/usr/local/lib/python3.12/dist-packages/pl_bolts/losses/self_supervised_learning.py:228: UnderReviewWarning: The feature AmdimNCELoss is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  self.nce_loss = AmdimNCELoss(tclip)
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
[2026-03-12 09:23:08,814][matplotlib.style.core][WARNING] - In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
[2026-03-12 09:23:08,814][matplotlib.style.core][WARNING] - In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/usr/local/lib/python3.12/dist-packages/hydra/_internal/instantiate/_instantiate2.py:92: UnderReviewWarning: The feature LinearWarmupCosineAnnealingLR is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  return _target_(*args, **kwargs)

  | Name     | Type       | Params
----------------------------------------
0 | model    | Sequential | 8.2 M
1 | ctc_loss | CTCLoss    | 0
2 | metrics  | ModuleDict | 0
----------------------------------------
8.2 M     Trainable params
0         Non-trainable params
8.2 M     Total params
32.657    Total estimated model params size (MB)

Sanity Checking: 0it [00:00, ?it/s]/usr/local/lib/python3.12/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/usr/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=3616) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

Sanity Checking:   0%|          | 0/2 [00:00<?, ?it/s]
Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Sanity Checking DataLoader 0: 100%|██████████| 2/2 [00:00<00:00,  4.36it/s]

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Training: 0it [00:00, ?it/s]
Training:   0%|          | 0/127 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/127 [00:00<?, ?it/s]
Epoch 0:  16%|█▌        | 20/127 [00:09<00:49,  2.17it/s]
Epoch 0:  16%|█▌        | 20/127 [00:09<00:49,  2.16it/s, loss=125, v_num=0]
Epoch 0:  31%|███▏      | 40/127 [00:17<00:38,  2.28it/s, loss=125, v_num=0]
Epoch 0:  31%|███▏      | 40/127 [00:17<00:38,  2.28it/s, loss=135, v_num=0]
Epoch 0:  47%|████▋     | 60/127 [00:25<00:28,  2.33it/s, loss=135, v_num=0]
Epoch 0:  47%|████▋     | 60/127 [00:25<00:28,  2.33it/s, loss=139, v_num=0]
Epoch 0:  63%|██████▎   | 80/127 [00:33<00:19,  2.36it/s, loss=139, v_num=0]
Epoch 0:  63%|██████▎   | 80/127 [00:33<00:19,  2.36it/s, loss=138, v_num=0]
Epoch 0:  79%|███████▊  | 100/127 [00:41<00:11,  2.38it/s, loss=138, v_num=0]
Epoch 0:  79%|███████▊  | 100/127 [00:42<00:11,  2.38it/s, loss=138, v_num=0]
Epoch 0:  94%|█████████▍| 120/127 [00:50<00:02,  2.38it/s, loss=138, v_num=0]
Epoch 0:  94%|█████████▍| 120/127 [00:50<00:02,  2.38it/s, loss=139, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.06it/s]
Epoch 0: 100%|██████████| 127/127 [00:53<00:00,  2.40it/s, loss=139, v_num=0]
Epoch 0: 100%|██████████| 127/127 [00:53<00:00,  2.39it/s, loss=139, v_num=0]


Epoch 0: 100%|██████████| 127/127 [00:53<00:00,  2.39it/s, loss=139, v_num=0]Epoch 0, global step 120: 'val/CER' reached 1816.70361 (best 1816.70361), saving model to '/content/drive/MyDrive/ECE_C247A_Final_Project/logs/2026-03-12/09-23-06/checkpoints/epoch=0-step=120.ckpt' as top 1

Epoch 0:   0%|          | 0/127 [00:00<?, ?it/s, loss=139, v_num=0]
Epoch 1:   0%|          | 0/127 [00:00<?, ?it/s, loss=139, v_num=0]
Epoch 1:  16%|█▌        | 20/127 [00:08<00:43,  2.45it/s, loss=139, v_num=0]
Epoch 1:  16%|█▌        | 20/127 [00:08<00:43,  2.44it/s, loss=52.3, v_num=0]
Epoch 1:  31%|███▏      | 40/127 [00:15<00:34,  2.52it/s, loss=52.3, v_num=0]
Epoch 1:  31%|███▏      | 40/127 [00:15<00:34,  2.52it/s, loss=7.85, v_num=0]
Epoch 1:  47%|████▋     | 60/127 [00:23<00:26,  2.54it/s, loss=7.85, v_num=0]
Epoch 1:  47%|████▋     | 60/127 [00:23<00:26,  2.53it/s, loss=5.31, v_num=0]
Epoch 1:  63%|██████▎   | 80/127 [00:31<00:18,  2.54it/s, loss=5.31, v_num=0]
Epoch 1:  63%|██████▎   | 80/127 [00:31<00:18,  2.54it/s, loss=3.98, v_num=0]
Epoch 1:  79%|███████▊  | 100/127 [00:40<00:10,  2.50it/s, loss=3.98, v_num=0]
Epoch 1:  79%|███████▊  | 100/127 [00:40<00:10,  2.50it/s, loss=3.83, v_num=0]
Epoch 1:  94%|█████████▍| 120/127 [00:47<00:02,  2.52it/s, loss=3.83, v_num=0]
Epoch 1:  94%|█████████▍| 120/127 [00:47<00:02,  2.52it/s, loss=3.74, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.31it/s]
Epoch 1: 100%|██████████| 127/127 [00:49<00:00,  2.54it/s, loss=3.74, v_num=0]
Epoch 1: 100%|██████████| 127/127 [00:49<00:00,  2.54it/s, loss=3.74, v_num=0]


Epoch 1: 100%|██████████| 127/127 [00:49<00:00,  2.54it/s, loss=3.74, v_num=0]Epoch 1, global step 240: 'val/CER' reached 100.00000 (best 100.00000), saving model to '/content/drive/MyDrive/ECE_C247A_Final_Project/logs/2026-03-12/09-23-06/checkpoints/epoch=1-step=240.ckpt' as top 1

Epoch 1:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.74, v_num=0]
Epoch 2:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.74, v_num=0]
Epoch 2:  16%|█▌        | 20/127 [00:08<00:42,  2.49it/s, loss=3.74, v_num=0]
Epoch 2:  16%|█▌        | 20/127 [00:08<00:43,  2.48it/s, loss=3.68, v_num=0]
Epoch 2:  31%|███▏      | 40/127 [00:17<00:37,  2.29it/s, loss=3.68, v_num=0]
Epoch 2:  31%|███▏      | 40/127 [00:17<00:37,  2.29it/s, loss=3.44, v_num=0]
Epoch 2:  47%|████▋     | 60/127 [00:25<00:28,  2.37it/s, loss=3.44, v_num=0]
Epoch 2:  47%|████▋     | 60/127 [00:25<00:28,  2.37it/s, loss=3.38, v_num=0]
Epoch 2:  63%|██████▎   | 80/127 [00:33<00:19,  2.42it/s, loss=3.38, v_num=0]
Epoch 2:  63%|██████▎   | 80/127 [00:33<00:19,  2.42it/s, loss=3.46, v_num=0]
Epoch 2:  79%|███████▊  | 100/127 [00:40<00:11,  2.45it/s, loss=3.46, v_num=0]
Epoch 2:  79%|███████▊  | 100/127 [00:40<00:11,  2.45it/s, loss=3.34, v_num=0]
Epoch 2:  94%|█████████▍| 120/127 [00:48<00:02,  2.48it/s, loss=3.34, v_num=0]
Epoch 2:  94%|█████████▍| 120/127 [00:48<00:02,  2.48it/s, loss=3.33, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.35it/s]
Epoch 2: 100%|██████████| 127/127 [00:50<00:00,  2.51it/s, loss=3.33, v_num=0]
Epoch 2: 100%|██████████| 127/127 [00:50<00:00,  2.51it/s, loss=3.33, v_num=0]


Epoch 2: 100%|██████████| 127/127 [00:50<00:00,  2.51it/s, loss=3.33, v_num=0]Epoch 2, global step 360: 'val/CER' was not in top 1

Epoch 2:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.33, v_num=0]
Epoch 3:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.33, v_num=0]
Epoch 3:  16%|█▌        | 20/127 [00:07<00:42,  2.51it/s, loss=3.33, v_num=0]
Epoch 3:  16%|█▌        | 20/127 [00:08<00:42,  2.50it/s, loss=3.35, v_num=0]
Epoch 3:  31%|███▏      | 40/127 [00:15<00:34,  2.53it/s, loss=3.35, v_num=0]
Epoch 3:  31%|███▏      | 40/127 [00:15<00:34,  2.52it/s, loss=3.29, v_num=0]
Epoch 3:  47%|████▋     | 60/127 [00:23<00:26,  2.55it/s, loss=3.29, v_num=0]
Epoch 3:  47%|████▋     | 60/127 [00:23<00:26,  2.55it/s, loss=3.32, v_num=0]
Epoch 3:  63%|██████▎   | 80/127 [00:31<00:18,  2.56it/s, loss=3.32, v_num=0]
Epoch 3:  63%|██████▎   | 80/127 [00:31<00:18,  2.56it/s, loss=3.27, v_num=0]
Epoch 3:  79%|███████▊  | 100/127 [00:38<00:10,  2.57it/s, loss=3.27, v_num=0]
Epoch 3:  79%|███████▊  | 100/127 [00:39<00:10,  2.56it/s, loss=3.28, v_num=0]
Epoch 3:  94%|█████████▍| 120/127 [00:46<00:02,  2.58it/s, loss=3.28, v_num=0]
Epoch 3:  94%|█████████▍| 120/127 [00:46<00:02,  2.58it/s, loss=3.26, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.47it/s]
Epoch 3: 100%|██████████| 127/127 [00:48<00:00,  2.60it/s, loss=3.26, v_num=0]
Epoch 3: 100%|██████████| 127/127 [00:48<00:00,  2.60it/s, loss=3.26, v_num=0]


Epoch 3: 100%|██████████| 127/127 [00:48<00:00,  2.60it/s, loss=3.26, v_num=0]Epoch 3, global step 480: 'val/CER' was not in top 1

Epoch 3:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.26, v_num=0]
Epoch 4:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.26, v_num=0]
Epoch 4:  16%|█▌        | 20/127 [00:08<00:43,  2.47it/s, loss=3.26, v_num=0]
Epoch 4:  16%|█▌        | 20/127 [00:08<00:43,  2.46it/s, loss=3.25, v_num=0]
Epoch 4:  31%|███▏      | 40/127 [00:15<00:34,  2.51it/s, loss=3.25, v_num=0]
Epoch 4:  31%|███▏      | 40/127 [00:15<00:34,  2.51it/s, loss=3.22, v_num=0]
Epoch 4:  47%|████▋     | 60/127 [00:23<00:26,  2.55it/s, loss=3.22, v_num=0]
Epoch 4:  47%|████▋     | 60/127 [00:23<00:26,  2.55it/s, loss=3.21, v_num=0]
Epoch 4:  63%|██████▎   | 80/127 [00:31<00:18,  2.55it/s, loss=3.21, v_num=0]
Epoch 4:  63%|██████▎   | 80/127 [00:31<00:18,  2.55it/s, loss=3.18, v_num=0]
Epoch 4:  79%|███████▊  | 100/127 [00:39<00:10,  2.55it/s, loss=3.18, v_num=0]
Epoch 4:  79%|███████▊  | 100/127 [00:39<00:10,  2.55it/s, loss=3.22, v_num=0]
Epoch 4:  94%|█████████▍| 120/127 [00:46<00:02,  2.56it/s, loss=3.22, v_num=0]
Epoch 4:  94%|█████████▍| 120/127 [00:46<00:02,  2.56it/s, loss=3.15, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.27it/s]
Epoch 4: 100%|██████████| 127/127 [00:49<00:00,  2.58it/s, loss=3.15, v_num=0]
Epoch 4: 100%|██████████| 127/127 [00:49<00:00,  2.58it/s, loss=3.15, v_num=0]


Epoch 4: 100%|██████████| 127/127 [00:49<00:00,  2.58it/s, loss=3.15, v_num=0]Epoch 4, global step 600: 'val/CER' was not in top 1

Epoch 4:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.15, v_num=0]
Epoch 5:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.15, v_num=0]
Epoch 5:  16%|█▌        | 20/127 [00:08<00:43,  2.48it/s, loss=3.15, v_num=0]
Epoch 5:  16%|█▌        | 20/127 [00:08<00:43,  2.47it/s, loss=3.13, v_num=0]
Epoch 5:  31%|███▏      | 40/127 [00:15<00:34,  2.52it/s, loss=3.13, v_num=0]
Epoch 5:  31%|███▏      | 40/127 [00:15<00:34,  2.51it/s, loss=3.16, v_num=0]
Epoch 5:  47%|████▋     | 60/127 [00:23<00:26,  2.53it/s, loss=3.16, v_num=0]
Epoch 5:  47%|████▋     | 60/127 [00:23<00:26,  2.53it/s, loss=3.21, v_num=0]
Epoch 5:  63%|██████▎   | 80/127 [00:31<00:18,  2.54it/s, loss=3.21, v_num=0]
Epoch 5:  63%|██████▎   | 80/127 [00:31<00:18,  2.54it/s, loss=3.09, v_num=0]
Epoch 5:  79%|███████▊  | 100/127 [00:39<00:10,  2.55it/s, loss=3.09, v_num=0]
Epoch 5:  79%|███████▊  | 100/127 [00:39<00:10,  2.55it/s, loss=3.15, v_num=0]

,channels,selected_channels,in_features,best_val_CER,final_val_CER,final_test_CER
0,16,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",528,17.34604,17.346035,19.250757

============================================================
Running experiment with 12 channels
Selected channels: [0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14]
in_features: 396
============================================================

[2026-03-12 10:05:17,645][__main__][INFO] -
Config:
user: single_user
dataset:
  train:
  - user: 89335547
    session: 2021-06-03-1622765527-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-02-1622681518-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-04-1622863166-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627003020-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-21-1626916256-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627004019-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622885888-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-02-1622679967-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-03-1622764398-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-21-1626917264-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622889105-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-03-1622766673-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-04-1622861066-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627001995-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622884635-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-21-1626915176-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  val:
  - user: 89335547
    session: 2021-06-04-1622862148-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  test:
  - user: 89335547
    session: 2021-06-02-1622682789-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  root: ${hydra:runtime.cwd}/data
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields:
  - emg_left
  - emg_right
band_rotation:
  _target_: emg2qwerty.transforms.ForEach
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets:
    - -1
    - 0
    - 1
temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120
logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16
specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 25
  n_freq_masks: 2
  freq_mask_param: 4
transforms:
  train:
  - ${to_tensor}
  - ${band_rotation}
  - ${temporal_jitter}
  - ${logspec}
  - ${specaug}
  val:
  - ${to_tensor}
  - ${logspec}
  test: ${transforms.val}
module:
  _target_: emg2qwerty.lightning.TDSConvLSTMCTCModule
  in_features: 396
  mlp_features:
  - 384
  block_channels:
  - 24
  - 24
  - 24
  kernel_width: 32
  lstm_hidden_size: 256
  lstm_num_layers: 2
  lstm_dropout: 0.2
  electrode_channels: 12
  selected_channels:
  - 0
  - 1
  - 2
  - 4
  - 5
  - 6
  - 8
  - 9
  - 10
  - 12
  - 13
  - 14
datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding:
  - 1800
  - 200
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0005
lr_scheduler:
  scheduler:
    _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
    warmup_epochs: 10
    max_epochs: ${trainer.max_epochs}
    warmup_start_lr: 1.0e-08
    eta_min: 1.0e-06
  interval: epoch
decoder:
  _target_: emg2qwerty.decoder.CTCGreedyDecoder
seed: 1501
batch_size: 32
num_workers: 2
train: true
checkpoint: null
monitor_metric: val/CER
monitor_mode: min
trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 50
  default_root_dir: ${hydra:runtime.output_dir}
callbacks:
- _target_: pytorch_lightning.callbacks.LearningRateMonitor
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${hydra:runtime.output_dir}/checkpoints
  monitor: ${monitor_metric}
  mode: ${monitor_mode}
  save_last: true
  verbose: true

Global seed set to 1501
[2026-03-12 10:05:17,648][__main__][INFO] - Instantiating LightningModule {'_target_': 'emg2qwerty.lightning.TDSConvLSTMCTCModule', 'in_features': 396, 'mlp_features': [384], 'block_channels': [24, 24, 24], 'kernel_width': 32, 'lstm_hidden_size': 256, 'lstm_num_layers': 2, 'lstm_dropout': 0.2, 'electrode_channels': 12, 'selected_channels': [0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14]}
Num LSTM layers:  2
Layer size:  256
[2026-03-12 10:05:17,787][__main__][INFO] - Instantiating LightningDataModule {'_target_': 'emg2qwerty.lightning.WindowedEMGDataModule', 'window_length': 8000, 'padding': [1800, 200]}
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: /content/drive/MyDrive/ECE_C247A_Final_Project/logs/2026-03-12/10-05-17/lightning_logs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/usr/local/lib/python3.12/dist-packages/pl_bolts/__init__.py:11: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(numpy, tp_name):
/usr/local/lib/python3.12/dist-packages/pl_bolts/__init__.py:11: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  if not hasattr(numpy, tp_name):
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:34: UnderReviewWarning: The feature generate_power_seq is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  "lr_options": generate_power_seq(LEARNING_RATE_CIFAR, 11),
/usr/local/lib/python3.12/dist-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:92: UnderReviewWarning: The feature FeatureMapContrastiveTask is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  contrastive_task: Union[FeatureMapContrastiveTask] = FeatureMapContrastiveTask("01, 02, 11"),
/usr/local/lib/python3.12/dist-packages/pl_bolts/losses/self_supervised_learning.py:228: UnderReviewWarning: The feature AmdimNCELoss is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  self.nce_loss = AmdimNCELoss(tclip)
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
[2026-03-12 10:05:19,329][matplotlib.style.core][WARNING] - In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
[2026-03-12 10:05:19,330][matplotlib.style.core][WARNING] - In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/usr/local/lib/python3.12/dist-packages/hydra/_internal/instantiate/_instantiate2.py:92: UnderReviewWarning: The feature LinearWarmupCosineAnnealingLR is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  return _target_(*args, **kwargs)

  | Name     | Type       | Params
----------------------------------------
0 | model    | Sequential | 8.1 M
1 | ctc_loss | CTCLoss    | 0
2 | metrics  | ModuleDict | 0
----------------------------------------
8.1 M     Trainable params
0         Non-trainable params
8.1 M     Total params
32.252    Total estimated model params size (MB)

Sanity Checking: 0it [00:00, ?it/s]/usr/local/lib/python3.12/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/usr/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=14573) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

Sanity Checking:   0%|          | 0/2 [00:00<?, ?it/s]
Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Sanity Checking DataLoader 0: 100%|██████████| 2/2 [00:00<00:00,  3.87it/s]

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Training: 0it [00:00, ?it/s]
Training:   0%|          | 0/127 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/127 [00:00<?, ?it/s]
Epoch 0:  16%|█▌        | 20/127 [00:09<00:49,  2.17it/s]
Epoch 0:  16%|█▌        | 20/127 [00:09<00:49,  2.16it/s, loss=141, v_num=0]
Epoch 0:  31%|███▏      | 40/127 [00:17<00:37,  2.29it/s, loss=141, v_num=0]
Epoch 0:  31%|███▏      | 40/127 [00:17<00:38,  2.29it/s, loss=122, v_num=0]
Epoch 0:  47%|████▋     | 60/127 [00:25<00:28,  2.34it/s, loss=122, v_num=0]
Epoch 0:  47%|████▋     | 60/127 [00:25<00:28,  2.34it/s, loss=130, v_num=0]
Epoch 0:  63%|██████▎   | 80/127 [00:33<00:19,  2.36it/s, loss=130, v_num=0]
Epoch 0:  63%|██████▎   | 80/127 [00:33<00:19,  2.36it/s, loss=134, v_num=0]
Epoch 0:  79%|███████▊  | 100/127 [00:42<00:11,  2.38it/s, loss=134, v_num=0]
Epoch 0:  79%|███████▊  | 100/127 [00:42<00:11,  2.38it/s, loss=123, v_num=0]
Epoch 0:  94%|█████████▍| 120/127 [00:49<00:02,  2.40it/s, loss=123, v_num=0]
Epoch 0:  94%|█████████▍| 120/127 [00:49<00:02,  2.40it/s, loss=130, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  3.85it/s]
Epoch 0: 100%|██████████| 127/127 [00:52<00:00,  2.42it/s, loss=130, v_num=0]
Epoch 0: 100%|██████████| 127/127 [00:52<00:00,  2.42it/s, loss=130, v_num=0]


Epoch 0: 100%|██████████| 127/127 [00:52<00:00,  2.42it/s, loss=130, v_num=0]Epoch 0, global step 120: 'val/CER' reached 1874.72314 (best 1874.72314), saving model to '/content/drive/MyDrive/ECE_C247A_Final_Project/logs/2026-03-12/10-05-17/checkpoints/epoch=0-step=120.ckpt' as top 1

Epoch 0:   0%|          | 0/127 [00:00<?, ?it/s, loss=130, v_num=0]
Epoch 1:   0%|          | 0/127 [00:00<?, ?it/s, loss=130, v_num=0]
Epoch 1:  16%|█▌        | 20/127 [00:08<00:43,  2.46it/s, loss=130, v_num=0]
Epoch 1:  16%|█▌        | 20/127 [00:08<00:43,  2.46it/s, loss=40.5, v_num=0]
Epoch 1:  31%|███▏      | 40/127 [00:16<00:34,  2.49it/s, loss=40.5, v_num=0]
Epoch 1:  31%|███▏      | 40/127 [00:16<00:34,  2.49it/s, loss=6.92, v_num=0]
Epoch 1:  47%|████▋     | 60/127 [00:23<00:26,  2.52it/s, loss=6.92, v_num=0]
Epoch 1:  47%|████▋     | 60/127 [00:23<00:26,  2.51it/s, loss=5.68, v_num=0]
Epoch 1:  63%|██████▎   | 80/127 [00:31<00:18,  2.52it/s, loss=5.68, v_num=0]
Epoch 1:  63%|██████▎   | 80/127 [00:31<00:18,  2.52it/s, loss=4.17, v_num=0]
Epoch 1:  79%|███████▊  | 100/127 [00:39<00:10,  2.53it/s, loss=4.17, v_num=0]
Epoch 1:  79%|███████▊  | 100/127 [00:39<00:10,  2.53it/s, loss=3.84, v_num=0]
Epoch 1:  94%|█████████▍| 120/127 [00:47<00:02,  2.53it/s, loss=3.84, v_num=0]
Epoch 1:  94%|█████████▍| 120/127 [00:47<00:02,  2.53it/s, loss=3.66, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  3.93it/s]
Epoch 1: 100%|██████████| 127/127 [00:49<00:00,  2.54it/s, loss=3.66, v_num=0]
Epoch 1: 100%|██████████| 127/127 [00:49<00:00,  2.54it/s, loss=3.66, v_num=0]


Epoch 1: 100%|██████████| 127/127 [00:49<00:00,  2.54it/s, loss=3.66, v_num=0]Epoch 1, global step 240: 'val/CER' reached 100.00000 (best 100.00000), saving model to '/content/drive/MyDrive/ECE_C247A_Final_Project/logs/2026-03-12/10-05-17/checkpoints/epoch=1-step=240.ckpt' as top 1

Epoch 1:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.66, v_num=0]
Epoch 2:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.66, v_num=0]
Epoch 2:  16%|█▌        | 20/127 [00:08<00:43,  2.46it/s, loss=3.66, v_num=0]
Epoch 2:  16%|█▌        | 20/127 [00:08<00:43,  2.45it/s, loss=3.65, v_num=0]
Epoch 2:  31%|███▏      | 40/127 [00:16<00:36,  2.37it/s, loss=3.65, v_num=0]
Epoch 2:  31%|███▏      | 40/127 [00:16<00:36,  2.37it/s, loss=3.45, v_num=0]
Epoch 2:  47%|████▋     | 60/127 [00:24<00:27,  2.43it/s, loss=3.45, v_num=0]
Epoch 2:  47%|████▋     | 60/127 [00:24<00:27,  2.43it/s, loss=3.39, v_num=0]
Epoch 2:  63%|██████▎   | 80/127 [00:32<00:19,  2.46it/s, loss=3.39, v_num=0]
Epoch 2:  63%|██████▎   | 80/127 [00:32<00:19,  2.46it/s, loss=3.43, v_num=0]
Epoch 2:  79%|███████▊  | 100/127 [00:40<00:10,  2.49it/s, loss=3.43, v_num=0]
Epoch 2:  79%|███████▊  | 100/127 [00:40<00:10,  2.49it/s, loss=3.34, v_num=0]
Epoch 2:  94%|█████████▍| 120/127 [00:47<00:02,  2.50it/s, loss=3.34, v_num=0]
Epoch 2:  94%|█████████▍| 120/127 [00:47<00:02,  2.50it/s, loss=3.3, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.20it/s]
Epoch 2: 100%|██████████| 127/127 [00:50<00:00,  2.52it/s, loss=3.3, v_num=0]
Epoch 2: 100%|██████████| 127/127 [00:50<00:00,  2.52it/s, loss=3.3, v_num=0]


Epoch 2: 100%|██████████| 127/127 [00:50<00:00,  2.52it/s, loss=3.3, v_num=0]Epoch 2, global step 360: 'val/CER' was not in top 1

Epoch 2:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.3, v_num=0]
Epoch 3:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.3, v_num=0]
Epoch 3:  16%|█▌        | 20/127 [00:08<00:43,  2.46it/s, loss=3.3, v_num=0]
Epoch 3:  16%|█▌        | 20/127 [00:08<00:43,  2.45it/s, loss=3.32, v_num=0]
Epoch 3:  31%|███▏      | 40/127 [00:15<00:34,  2.52it/s, loss=3.32, v_num=0]
Epoch 3:  31%|███▏      | 40/127 [00:15<00:34,  2.51it/s, loss=3.26, v_num=0]
Epoch 3:  47%|████▋     | 60/127 [00:23<00:26,  2.54it/s, loss=3.26, v_num=0]
Epoch 3:  47%|████▋     | 60/127 [00:23<00:26,  2.54it/s, loss=3.26, v_num=0]
Epoch 3:  63%|██████▎   | 80/127 [00:31<00:18,  2.56it/s, loss=3.26, v_num=0]
Epoch 3:  63%|██████▎   | 80/127 [00:31<00:18,  2.56it/s, loss=3.27, v_num=0]
Epoch 3:  79%|███████▊  | 100/127 [00:38<00:10,  2.57it/s, loss=3.27, v_num=0]
Epoch 3:  79%|███████▊  | 100/127 [00:38<00:10,  2.57it/s, loss=3.29, v_num=0]
Epoch 3:  94%|█████████▍| 120/127 [00:46<00:02,  2.57it/s, loss=3.29, v_num=0]
Epoch 3:  94%|█████████▍| 120/127 [00:46<00:02,  2.57it/s, loss=3.25, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.20it/s]
Epoch 3: 100%|██████████| 127/127 [00:49<00:00,  2.59it/s, loss=3.25, v_num=0]
Epoch 3: 100%|██████████| 127/127 [00:49<00:00,  2.59it/s, loss=3.25, v_num=0]


Epoch 3: 100%|██████████| 127/127 [00:49<00:00,  2.59it/s, loss=3.25, v_num=0]Epoch 3, global step 480: 'val/CER' was not in top 1

Epoch 3:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.25, v_num=0]
Epoch 4:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.25, v_num=0]
Epoch 4:  16%|█▌        | 20/127 [00:07<00:42,  2.52it/s, loss=3.25, v_num=0]
Epoch 4:  16%|█▌        | 20/127 [00:07<00:42,  2.51it/s, loss=3.17, v_num=0]
Epoch 4:  31%|███▏      | 40/127 [00:15<00:34,  2.53it/s, loss=3.17, v_num=0]
Epoch 4:  31%|███▏      | 40/127 [00:15<00:34,  2.53it/s, loss=3.2, v_num=0]
Epoch 4:  47%|████▋     | 60/127 [00:23<00:26,  2.56it/s, loss=3.2, v_num=0]
Epoch 4:  47%|████▋     | 60/127 [00:23<00:26,  2.56it/s, loss=3.19, v_num=0]
Epoch 4:  63%|██████▎   | 80/127 [00:31<00:18,  2.56it/s, loss=3.19, v_num=0]
Epoch 4:  63%|██████▎   | 80/127 [00:31<00:18,  2.56it/s, loss=3.22, v_num=0]
Epoch 4:  79%|███████▊  | 100/127 [00:38<00:10,  2.57it/s, loss=3.22, v_num=0]
Epoch 4:  79%|███████▊  | 100/127 [00:38<00:10,  2.56it/s, loss=3.2, v_num=0]
Epoch 4:  94%|█████████▍| 120/127 [00:46<00:02,  2.57it/s, loss=3.2, v_num=0]
Epoch 4:  94%|█████████▍| 120/127 [00:46<00:02,  2.57it/s, loss=3.18, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.51it/s]
Epoch 4: 100%|██████████| 127/127 [00:48<00:00,  2.60it/s, loss=3.18, v_num=0]
Epoch 4: 100%|██████████| 127/127 [00:48<00:00,  2.60it/s, loss=3.18, v_num=0]


Epoch 4: 100%|██████████| 127/127 [00:48<00:00,  2.60it/s, loss=3.18, v_num=0]Epoch 4, global step 600: 'val/CER' was not in top 1

Epoch 4:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.18, v_num=0]
Epoch 5:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.18, v_num=0]
Epoch 5:  16%|█▌        | 20/127 [00:08<00:43,  2.47it/s, loss=3.18, v_num=0]
Epoch 5:  16%|█▌        | 20/127 [00:08<00:43,  2.46it/s, loss=3.14, v_num=0]
Epoch 5:  31%|███▏      | 40/127 [00:15<00:34,  2.52it/s, loss=3.14, v_num=0]
Epoch 5:  31%|███▏      | 40/127 [00:15<00:34,  2.52it/s, loss=3.1, v_num=0]
Epoch 5:  47%|████▋     | 60/127 [00:23<00:26,  2.54it/s, loss=3.1, v_num=0]
Epoch 5:  47%|████▋     | 60/127 [00:23<00:26,  2.53it/s, loss=3.11, v_num=0]
Epoch 5:  63%|██████▎   | 80/127 [00:31<00:18,  2.56it/s, loss=3.11, v_num=0]
Epoch 5:  63%|██████▎   | 80/127 [00:31<00:18,  2.56it/s, loss=3.25, v_num=0]
Epoch 5:  79%|███████▊  | 100/127 [00:38<00:10,  2.56it/s, loss=3.25, v_num=0]
Epoch 5:  79%|███████▊  | 100/127 [00:39<00:10,  2.56it/s, loss=3.12, v_num=0]

,channels,selected_channels,in_features,best_val_CER,final_val_CER,final_test_CER
0,16,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",528,17.34604,17.346035,19.250757
1,12,"[0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14]",396,19.60567,19.605671,21.004765

============================================================
Running experiment with 8 channels
Selected channels: [0, 2, 4, 6, 8, 10, 12, 14]
in_features: 264
============================================================

[2026-03-12 10:47:21,684][__main__][INFO] -
Config:
user: single_user
dataset:
  train:
  - user: 89335547
    session: 2021-06-03-1622765527-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-02-1622681518-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-04-1622863166-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627003020-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-21-1626916256-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627004019-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622885888-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-02-1622679967-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-03-1622764398-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-21-1626917264-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622889105-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-03-1622766673-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-04-1622861066-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627001995-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622884635-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-21-1626915176-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  val:
  - user: 89335547
    session: 2021-06-04-1622862148-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  test:
  - user: 89335547
    session: 2021-06-02-1622682789-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  root: ${hydra:runtime.cwd}/data
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields:
  - emg_left
  - emg_right
band_rotation:
  _target_: emg2qwerty.transforms.ForEach
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets:
    - -1
    - 0
    - 1
temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120
logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16
specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 25
  n_freq_masks: 2
  freq_mask_param: 4
transforms:
  train:
  - ${to_tensor}
  - ${band_rotation}
  - ${temporal_jitter}
  - ${logspec}
  - ${specaug}
  val:
  - ${to_tensor}
  - ${logspec}
  test: ${transforms.val}
module:
  _target_: emg2qwerty.lightning.TDSConvLSTMCTCModule
  in_features: 264
  mlp_features:
  - 384
  block_channels:
  - 24
  - 24
  - 24
  kernel_width: 32
  lstm_hidden_size: 256
  lstm_num_layers: 2
  lstm_dropout: 0.2
  electrode_channels: 8
  selected_channels:
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  - 12
  - 14
datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding:
  - 1800
  - 200
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0005
lr_scheduler:
  scheduler:
    _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
    warmup_epochs: 10
    max_epochs: ${trainer.max_epochs}
    warmup_start_lr: 1.0e-08
    eta_min: 1.0e-06
  interval: epoch
decoder:
  _target_: emg2qwerty.decoder.CTCGreedyDecoder
seed: 1501
batch_size: 32
num_workers: 2
train: true
checkpoint: null
monitor_metric: val/CER
monitor_mode: min
trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 50
  default_root_dir: ${hydra:runtime.output_dir}
callbacks:
- _target_: pytorch_lightning.callbacks.LearningRateMonitor
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${hydra:runtime.output_dir}/checkpoints
  monitor: ${monitor_metric}
  mode: ${monitor_mode}
  save_last: true
  verbose: true

Global seed set to 1501
[2026-03-12 10:47:21,687][__main__][INFO] - Instantiating LightningModule {'_target_': 'emg2qwerty.lightning.TDSConvLSTMCTCModule', 'in_features': 264, 'mlp_features': [384], 'block_channels': [24, 24, 24], 'kernel_width': 32, 'lstm_hidden_size': 256, 'lstm_num_layers': 2, 'lstm_dropout': 0.2, 'electrode_channels': 8, 'selected_channels': [0, 2, 4, 6, 8, 10, 12, 14]}
Num LSTM layers:  2
Layer size:  256
[2026-03-12 10:47:21,830][__main__][INFO] - Instantiating LightningDataModule {'_target_': 'emg2qwerty.lightning.WindowedEMGDataModule', 'window_length': 8000, 'padding': [1800, 200]}
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: /content/drive/MyDrive/ECE_C247A_Final_Project/logs/2026-03-12/10-47-21/lightning_logs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/usr/local/lib/python3.12/dist-packages/pl_bolts/__init__.py:11: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(numpy, tp_name):
/usr/local/lib/python3.12/dist-packages/pl_bolts/__init__.py:11: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  if not hasattr(numpy, tp_name):
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:34: UnderReviewWarning: The feature generate_power_seq is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  "lr_options": generate_power_seq(LEARNING_RATE_CIFAR, 11),
/usr/local/lib/python3.12/dist-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:92: UnderReviewWarning: The feature FeatureMapContrastiveTask is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  contrastive_task: Union[FeatureMapContrastiveTask] = FeatureMapContrastiveTask("01, 02, 11"),
/usr/local/lib/python3.12/dist-packages/pl_bolts/losses/self_supervised_learning.py:228: UnderReviewWarning: The feature AmdimNCELoss is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  self.nce_loss = AmdimNCELoss(tclip)
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
[2026-03-12 10:47:23,336][matplotlib.style.core][WARNING] - In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
[2026-03-12 10:47:23,337][matplotlib.style.core][WARNING] - In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/usr/local/lib/python3.12/dist-packages/hydra/_internal/instantiate/_instantiate2.py:92: UnderReviewWarning: The feature LinearWarmupCosineAnnealingLR is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  return _target_(*args, **kwargs)

  | Name     | Type       | Params
----------------------------------------
0 | model    | Sequential | 8.0 M
1 | ctc_loss | CTCLoss    | 0
2 | metrics  | ModuleDict | 0
----------------------------------------
8.0 M     Trainable params
0         Non-trainable params
8.0 M     Total params
31.846    Total estimated model params size (MB)

Sanity Checking: 0it [00:00, ?it/s]/usr/local/lib/python3.12/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/usr/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=25187) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

Sanity Checking:   0%|          | 0/2 [00:00<?, ?it/s]
Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Sanity Checking DataLoader 0: 100%|██████████| 2/2 [00:00<00:00,  4.46it/s]

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Training: 0it [00:00, ?it/s]
Training:   0%|          | 0/127 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/127 [00:00<?, ?it/s]
Epoch 0:  16%|█▌        | 20/127 [00:09<00:49,  2.15it/s]
Epoch 0:  16%|█▌        | 20/127 [00:09<00:49,  2.14it/s, loss=139, v_num=0]
Epoch 0:  31%|███▏      | 40/127 [00:17<00:38,  2.28it/s, loss=139, v_num=0]
Epoch 0:  31%|███▏      | 40/127 [00:17<00:38,  2.27it/s, loss=124, v_num=0]
Epoch 0:  47%|████▋     | 60/127 [00:25<00:28,  2.34it/s, loss=124, v_num=0]
Epoch 0:  47%|████▋     | 60/127 [00:25<00:28,  2.34it/s, loss=136, v_num=0]
Epoch 0:  63%|██████▎   | 80/127 [00:33<00:19,  2.37it/s, loss=136, v_num=0]
Epoch 0:  63%|██████▎   | 80/127 [00:33<00:19,  2.37it/s, loss=136, v_num=0]
Epoch 0:  79%|███████▊  | 100/127 [00:41<00:11,  2.39it/s, loss=136, v_num=0]
Epoch 0:  79%|███████▊  | 100/127 [00:41<00:11,  2.39it/s, loss=141, v_num=0]
Epoch 0:  94%|█████████▍| 120/127 [00:49<00:02,  2.42it/s, loss=141, v_num=0]
Epoch 0:  94%|█████████▍| 120/127 [00:49<00:02,  2.42it/s, loss=130, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.10it/s]
Epoch 0: 100%|██████████| 127/127 [00:52<00:00,  2.43it/s, loss=130, v_num=0]
Epoch 0: 100%|██████████| 127/127 [00:52<00:00,  2.43it/s, loss=130, v_num=0]


Epoch 0: 100%|██████████| 127/127 [00:52<00:00,  2.43it/s, loss=130, v_num=0]Epoch 0, global step 120: 'val/CER' reached 1518.58667 (best 1518.58667), saving model to '/content/drive/MyDrive/ECE_C247A_Final_Project/logs/2026-03-12/10-47-21/checkpoints/epoch=0-step=120.ckpt' as top 1

Epoch 0:   0%|          | 0/127 [00:00<?, ?it/s, loss=130, v_num=0]
Epoch 1:   0%|          | 0/127 [00:00<?, ?it/s, loss=130, v_num=0]
Epoch 1:  16%|█▌        | 20/127 [00:08<00:43,  2.44it/s, loss=130, v_num=0]
Epoch 1:  16%|█▌        | 20/127 [00:08<00:43,  2.43it/s, loss=55.6, v_num=0]
Epoch 1:  31%|███▏      | 40/127 [00:15<00:34,  2.50it/s, loss=55.6, v_num=0]
Epoch 1:  31%|███▏      | 40/127 [00:16<00:34,  2.50it/s, loss=13.1, v_num=0]
Epoch 1:  47%|████▋     | 60/127 [00:23<00:26,  2.52it/s, loss=13.1, v_num=0]
Epoch 1:  47%|████▋     | 60/127 [00:23<00:26,  2.52it/s, loss=5.79, v_num=0]
Epoch 1:  63%|██████▎   | 80/127 [00:31<00:18,  2.54it/s, loss=5.79, v_num=0]
Epoch 1:  63%|██████▎   | 80/127 [00:31<00:18,  2.54it/s, loss=4.55, v_num=0]
Epoch 1:  79%|███████▊  | 100/127 [00:39<00:10,  2.55it/s, loss=4.55, v_num=0]
Epoch 1:  79%|███████▊  | 100/127 [00:39<00:10,  2.55it/s, loss=4.06, v_num=0]
Epoch 1:  94%|█████████▍| 120/127 [00:46<00:02,  2.56it/s, loss=4.06, v_num=0]
Epoch 1:  94%|█████████▍| 120/127 [00:46<00:02,  2.56it/s, loss=3.79, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.00it/s]
Epoch 1: 100%|██████████| 127/127 [00:49<00:00,  2.57it/s, loss=3.79, v_num=0]
Epoch 1: 100%|██████████| 127/127 [00:49<00:00,  2.57it/s, loss=3.79, v_num=0]


Epoch 1: 100%|██████████| 127/127 [00:49<00:00,  2.57it/s, loss=3.79, v_num=0]Epoch 1, global step 240: 'val/CER' reached 100.00000 (best 100.00000), saving model to '/content/drive/MyDrive/ECE_C247A_Final_Project/logs/2026-03-12/10-47-21/checkpoints/epoch=1-step=240.ckpt' as top 1

Epoch 1:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.79, v_num=0]
Epoch 2:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.79, v_num=0]
Epoch 2:  16%|█▌        | 20/127 [00:08<00:43,  2.48it/s, loss=3.79, v_num=0]
Epoch 2:  16%|█▌        | 20/127 [00:08<00:43,  2.47it/s, loss=3.69, v_num=0]
Epoch 2:  31%|███▏      | 40/127 [00:17<00:38,  2.28it/s, loss=3.69, v_num=0]
Epoch 2:  31%|███▏      | 40/127 [00:17<00:38,  2.28it/s, loss=3.5, v_num=0]
Epoch 2:  47%|████▋     | 60/127 [00:25<00:28,  2.38it/s, loss=3.5, v_num=0]
Epoch 2:  47%|████▋     | 60/127 [00:25<00:28,  2.38it/s, loss=3.44, v_num=0]
Epoch 2:  63%|██████▎   | 80/127 [00:32<00:19,  2.43it/s, loss=3.44, v_num=0]
Epoch 2:  63%|██████▎   | 80/127 [00:32<00:19,  2.43it/s, loss=3.42, v_num=0]
Epoch 2:  79%|███████▊  | 100/127 [00:40<00:10,  2.46it/s, loss=3.42, v_num=0]
Epoch 2:  79%|███████▊  | 100/127 [00:40<00:10,  2.46it/s, loss=3.41, v_num=0]
Epoch 2:  94%|█████████▍| 120/127 [00:48<00:02,  2.48it/s, loss=3.41, v_num=0]
Epoch 2:  94%|█████████▍| 120/127 [00:48<00:02,  2.48it/s, loss=3.36, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.06it/s]
Epoch 2: 100%|██████████| 127/127 [00:50<00:00,  2.49it/s, loss=3.36, v_num=0]
Epoch 2: 100%|██████████| 127/127 [00:50<00:00,  2.49it/s, loss=3.36, v_num=0]


Epoch 2: 100%|██████████| 127/127 [00:50<00:00,  2.49it/s, loss=3.36, v_num=0]Epoch 2, global step 360: 'val/CER' was not in top 1

Epoch 2:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.36, v_num=0]
Epoch 3:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.36, v_num=0]
Epoch 3:  16%|█▌        | 20/127 [00:08<00:43,  2.46it/s, loss=3.36, v_num=0]
Epoch 3:  16%|█▌        | 20/127 [00:08<00:43,  2.46it/s, loss=3.3, v_num=0]
Epoch 3:  31%|███▏      | 40/127 [00:15<00:34,  2.52it/s, loss=3.3, v_num=0]
Epoch 3:  31%|███▏      | 40/127 [00:15<00:34,  2.52it/s, loss=3.32, v_num=0]
Epoch 3:  47%|████▋     | 60/127 [00:23<00:26,  2.55it/s, loss=3.32, v_num=0]
Epoch 3:  47%|████▋     | 60/127 [00:23<00:26,  2.54it/s, loss=3.34, v_num=0]
Epoch 3:  63%|██████▎   | 80/127 [00:31<00:18,  2.56it/s, loss=3.34, v_num=0]
Epoch 3:  63%|██████▎   | 80/127 [00:31<00:18,  2.56it/s, loss=3.26, v_num=0]
Epoch 3:  79%|███████▊  | 100/127 [00:38<00:10,  2.57it/s, loss=3.26, v_num=0]
Epoch 3:  79%|███████▊  | 100/127 [00:38<00:10,  2.57it/s, loss=3.31, v_num=0]
Epoch 3:  94%|█████████▍| 120/127 [00:46<00:02,  2.58it/s, loss=3.31, v_num=0]
Epoch 3:  94%|█████████▍| 120/127 [00:46<00:02,  2.58it/s, loss=3.2, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.05it/s]
Epoch 3: 100%|██████████| 127/127 [00:49<00:00,  2.59it/s, loss=3.2, v_num=0]
Epoch 3: 100%|██████████| 127/127 [00:49<00:00,  2.59it/s, loss=3.2, v_num=0]


Epoch 3: 100%|██████████| 127/127 [00:49<00:00,  2.59it/s, loss=3.2, v_num=0]Epoch 3, global step 480: 'val/CER' was not in top 1

Epoch 3:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.2, v_num=0]
Epoch 4:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.2, v_num=0]
Epoch 4:  16%|█▌        | 20/127 [00:08<00:42,  2.49it/s, loss=3.2, v_num=0]
Epoch 4:  16%|█▌        | 20/127 [00:08<00:43,  2.48it/s, loss=3.25, v_num=0]
Epoch 4:  31%|███▏      | 40/127 [00:15<00:34,  2.55it/s, loss=3.25, v_num=0]
Epoch 4:  31%|███▏      | 40/127 [00:15<00:34,  2.54it/s, loss=3.25, v_num=0]
Epoch 4:  47%|████▋     | 60/127 [00:23<00:26,  2.56it/s, loss=3.25, v_num=0]
Epoch 4:  47%|████▋     | 60/127 [00:23<00:26,  2.55it/s, loss=3.21, v_num=0]
Epoch 4:  63%|██████▎   | 80/127 [00:31<00:18,  2.56it/s, loss=3.21, v_num=0]
Epoch 4:  63%|██████▎   | 80/127 [00:31<00:18,  2.56it/s, loss=3.24, v_num=0]
Epoch 4:  79%|███████▊  | 100/127 [00:38<00:10,  2.58it/s, loss=3.24, v_num=0]
Epoch 4:  79%|███████▊  | 100/127 [00:38<00:10,  2.57it/s, loss=3.16, v_num=0]
Epoch 4:  94%|█████████▍| 120/127 [00:46<00:02,  2.58it/s, loss=3.16, v_num=0]
Epoch 4:  94%|█████████▍| 120/127 [00:46<00:02,  2.58it/s, loss=3.17, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  3.85it/s]
Epoch 4: 100%|██████████| 127/127 [00:49<00:00,  2.58it/s, loss=3.17, v_num=0]
Epoch 4: 100%|██████████| 127/127 [00:49<00:00,  2.58it/s, loss=3.17, v_num=0]


Epoch 4: 100%|██████████| 127/127 [00:49<00:00,  2.58it/s, loss=3.17, v_num=0]Epoch 4, global step 600: 'val/CER' was not in top 1

Epoch 4:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.17, v_num=0]
Epoch 5:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.17, v_num=0]
Epoch 5:  16%|█▌        | 20/127 [00:08<00:43,  2.48it/s, loss=3.17, v_num=0]
Epoch 5:  16%|█▌        | 20/127 [00:08<00:43,  2.47it/s, loss=3.12, v_num=0]
Epoch 5:  31%|███▏      | 40/127 [00:15<00:33,  2.56it/s, loss=3.12, v_num=0]
Epoch 5:  31%|███▏      | 40/127 [00:15<00:34,  2.55it/s, loss=3.16, v_num=0]
Epoch 5:  47%|████▋     | 60/127 [00:23<00:26,  2.57it/s, loss=3.16, v_num=0]
Epoch 5:  47%|████▋     | 60/127 [00:23<00:26,  2.57it/s, loss=3.19, v_num=0]
Epoch 5:  63%|██████▎   | 80/127 [00:31<00:18,  2.58it/s, loss=3.19, v_num=0]
Epoch 5:  63%|██████▎   | 80/127 [00:31<00:18,  2.57it/s, loss=3.11, v_num=0]
Epoch 5:  79%|███████▊  | 100/127 [00:38<00:10,  2.58it/s, loss=3.11, v_num=0]
Epoch 5:  79%|███████▊  | 100/127 [00:38<00:10,  2.58it/s, loss=3.08, v_num=0]
Epoch 5:  94%|█████████▍| 120/127 [00:46<00:02,  2.59it/s, loss=3.08, v_num=0]

,channels,selected_channels,in_features,best_val_CER,final_val_CER,final_test_CER
0,16,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",528,17.34604,17.346035,19.250757
1,12,"[0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14]",396,19.60567,19.605671,21.004765
2,8,"[0, 2, 4, 6, 8, 10, 12, 14]",264,20.04874,20.048737,22.867043

============================================================
Running experiment with 4 channels
Selected channels: [0, 4, 8, 12]
in_features: 132
============================================================

[2026-03-12 11:29:26,375][__main__][INFO] -
Config:
user: single_user
dataset:
  train:
  - user: 89335547
    session: 2021-06-03-1622765527-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-02-1622681518-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-04-1622863166-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627003020-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-21-1626916256-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627004019-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622885888-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-02-1622679967-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-03-1622764398-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-21-1626917264-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622889105-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-03-1622766673-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-04-1622861066-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627001995-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622884635-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-21-1626915176-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  val:
  - user: 89335547
    session: 2021-06-04-1622862148-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  test:
  - user: 89335547
    session: 2021-06-02-1622682789-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  root: ${hydra:runtime.cwd}/data
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields:
  - emg_left
  - emg_right
band_rotation:
  _target_: emg2qwerty.transforms.ForEach
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets:
    - -1
    - 0
    - 1
temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120
logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16
specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 25
  n_freq_masks: 2
  freq_mask_param: 4
transforms:
  train:
  - ${to_tensor}
  - ${band_rotation}
  - ${temporal_jitter}
  - ${logspec}
  - ${specaug}
  val:
  - ${to_tensor}
  - ${logspec}
  test: ${transforms.val}
module:
  _target_: emg2qwerty.lightning.TDSConvLSTMCTCModule
  in_features: 132
  mlp_features:
  - 384
  block_channels:
  - 24
  - 24
  - 24
  kernel_width: 32
  lstm_hidden_size: 256
  lstm_num_layers: 2
  lstm_dropout: 0.2
  electrode_channels: 4
  selected_channels:
  - 0
  - 4
  - 8
  - 12
datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding:
  - 1800
  - 200
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0005
lr_scheduler:
  scheduler:
    _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
    warmup_epochs: 10
    max_epochs: ${trainer.max_epochs}
    warmup_start_lr: 1.0e-08
    eta_min: 1.0e-06
  interval: epoch
decoder:
  _target_: emg2qwerty.decoder.CTCGreedyDecoder
seed: 1501
batch_size: 32
num_workers: 2
train: true
checkpoint: null
monitor_metric: val/CER
monitor_mode: min
trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 50
  default_root_dir: ${hydra:runtime.output_dir}
callbacks:
- _target_: pytorch_lightning.callbacks.LearningRateMonitor
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${hydra:runtime.output_dir}/checkpoints
  monitor: ${monitor_metric}
  mode: ${monitor_mode}
  save_last: true
  verbose: true

Global seed set to 1501
[2026-03-12 11:29:26,378][__main__][INFO] - Instantiating LightningModule {'_target_': 'emg2qwerty.lightning.TDSConvLSTMCTCModule', 'in_features': 132, 'mlp_features': [384], 'block_channels': [24, 24, 24], 'kernel_width': 32, 'lstm_hidden_size': 256, 'lstm_num_layers': 2, 'lstm_dropout': 0.2, 'electrode_channels': 4, 'selected_channels': [0, 4, 8, 12]}
Num LSTM layers:  2
Layer size:  256
[2026-03-12 11:29:26,521][__main__][INFO] - Instantiating LightningDataModule {'_target_': 'emg2qwerty.lightning.WindowedEMGDataModule', 'window_length': 8000, 'padding': [1800, 200]}
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: /content/drive/MyDrive/ECE_C247A_Final_Project/logs/2026-03-12/11-29-26/lightning_logs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/usr/local/lib/python3.12/dist-packages/pl_bolts/__init__.py:11: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(numpy, tp_name):
/usr/local/lib/python3.12/dist-packages/pl_bolts/__init__.py:11: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  if not hasattr(numpy, tp_name):
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:34: UnderReviewWarning: The feature generate_power_seq is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  "lr_options": generate_power_seq(LEARNING_RATE_CIFAR, 11),
/usr/local/lib/python3.12/dist-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:92: UnderReviewWarning: The feature FeatureMapContrastiveTask is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  contrastive_task: Union[FeatureMapContrastiveTask] = FeatureMapContrastiveTask("01, 02, 11"),
/usr/local/lib/python3.12/dist-packages/pl_bolts/losses/self_supervised_learning.py:228: UnderReviewWarning: The feature AmdimNCELoss is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  self.nce_loss = AmdimNCELoss(tclip)
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
[2026-03-12 11:29:28,102][matplotlib.style.core][WARNING] - In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
[2026-03-12 11:29:28,103][matplotlib.style.core][WARNING] - In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/usr/local/lib/python3.12/dist-packages/hydra/_internal/instantiate/_instantiate2.py:92: UnderReviewWarning: The feature LinearWarmupCosineAnnealingLR is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  return _target_(*args, **kwargs)

  | Name     | Type       | Params
----------------------------------------
0 | model    | Sequential | 7.9 M
1 | ctc_loss | CTCLoss    | 0
2 | metrics  | ModuleDict | 0
----------------------------------------
7.9 M     Trainable params
0         Non-trainable params
7.9 M     Total params
31.441    Total estimated model params size (MB)

Sanity Checking: 0it [00:00, ?it/s]/usr/local/lib/python3.12/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/usr/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=36234) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

Sanity Checking:   0%|          | 0/2 [00:00<?, ?it/s]
Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Sanity Checking DataLoader 0: 100%|██████████| 2/2 [00:00<00:00,  4.18it/s]

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Training: 0it [00:00, ?it/s]
Training:   0%|          | 0/127 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/127 [00:00<?, ?it/s]
Epoch 0:  16%|█▌        | 20/127 [00:09<00:49,  2.15it/s]
Epoch 0:  16%|█▌        | 20/127 [00:09<00:49,  2.14it/s, loss=133, v_num=0]
Epoch 0:  31%|███▏      | 40/127 [00:17<00:38,  2.25it/s, loss=133, v_num=0]
Epoch 0:  31%|███▏      | 40/127 [00:17<00:38,  2.24it/s, loss=129, v_num=0]
Epoch 0:  47%|████▋     | 60/127 [00:26<00:29,  2.28it/s, loss=129, v_num=0]
Epoch 0:  47%|████▋     | 60/127 [00:26<00:29,  2.27it/s, loss=132, v_num=0]
Epoch 0:  63%|██████▎   | 80/127 [00:34<00:20,  2.30it/s, loss=132, v_num=0]
Epoch 0:  63%|██████▎   | 80/127 [00:34<00:20,  2.30it/s, loss=138, v_num=0]
Epoch 0:  79%|███████▊  | 100/127 [00:43<00:11,  2.32it/s, loss=138, v_num=0]
Epoch 0:  79%|███████▊  | 100/127 [00:43<00:11,  2.32it/s, loss=145, v_num=0]
Epoch 0:  94%|█████████▍| 120/127 [00:51<00:02,  2.34it/s, loss=145, v_num=0]
Epoch 0:  94%|█████████▍| 120/127 [00:51<00:02,  2.34it/s, loss=125, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.01it/s]
Epoch 0: 100%|██████████| 127/127 [00:53<00:00,  2.36it/s, loss=125, v_num=0]
Epoch 0: 100%|██████████| 127/127 [00:53<00:00,  2.36it/s, loss=125, v_num=0]


Epoch 0: 100%|██████████| 127/127 [00:53<00:00,  2.36it/s, loss=125, v_num=0]Epoch 0, global step 120: 'val/CER' reached 1546.07886 (best 1546.07886), saving model to '/content/drive/MyDrive/ECE_C247A_Final_Project/logs/2026-03-12/11-29-26/checkpoints/epoch=0-step=120.ckpt' as top 1

Epoch 0:   0%|          | 0/127 [00:00<?, ?it/s, loss=125, v_num=0]
Epoch 1:   0%|          | 0/127 [00:00<?, ?it/s, loss=125, v_num=0]
Epoch 1:  16%|█▌        | 20/127 [00:08<00:44,  2.41it/s, loss=125, v_num=0]
Epoch 1:  16%|█▌        | 20/127 [00:08<00:44,  2.40it/s, loss=74, v_num=0]
Epoch 1:  31%|███▏      | 40/127 [00:16<00:35,  2.42it/s, loss=74, v_num=0]
Epoch 1:  31%|███▏      | 40/127 [00:16<00:36,  2.42it/s, loss=26, v_num=0]
Epoch 1:  47%|████▋     | 60/127 [00:24<00:27,  2.44it/s, loss=26, v_num=0]
Epoch 1:  47%|████▋     | 60/127 [00:24<00:27,  2.44it/s, loss=5.96, v_num=0]
Epoch 1:  63%|██████▎   | 80/127 [00:32<00:19,  2.45it/s, loss=5.96, v_num=0]
Epoch 1:  63%|██████▎   | 80/127 [00:32<00:19,  2.45it/s, loss=4.89, v_num=0]
Epoch 1:  79%|███████▊  | 100/127 [00:40<00:10,  2.46it/s, loss=4.89, v_num=0]
Epoch 1:  79%|███████▊  | 100/127 [00:40<00:10,  2.46it/s, loss=4.01, v_num=0]
Epoch 1:  94%|█████████▍| 120/127 [00:48<00:02,  2.47it/s, loss=4.01, v_num=0]
Epoch 1:  94%|█████████▍| 120/127 [00:48<00:02,  2.47it/s, loss=3.71, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.18it/s]
Epoch 1: 100%|██████████| 127/127 [00:51<00:00,  2.49it/s, loss=3.71, v_num=0]
Epoch 1: 100%|██████████| 127/127 [00:51<00:00,  2.49it/s, loss=3.71, v_num=0]


Epoch 1: 100%|██████████| 127/127 [00:51<00:00,  2.49it/s, loss=3.71, v_num=0]Epoch 1, global step 240: 'val/CER' reached 100.00000 (best 100.00000), saving model to '/content/drive/MyDrive/ECE_C247A_Final_Project/logs/2026-03-12/11-29-26/checkpoints/epoch=1-step=240.ckpt' as top 1

Epoch 1:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.71, v_num=0]
Epoch 2:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.71, v_num=0]
Epoch 2:  16%|█▌        | 20/127 [00:09<00:53,  2.01it/s, loss=3.71, v_num=0]
Epoch 2:  16%|█▌        | 20/127 [00:09<00:53,  2.01it/s, loss=3.64, v_num=0]
Epoch 2:  31%|███▏      | 40/127 [00:17<00:38,  2.23it/s, loss=3.64, v_num=0]
Epoch 2:  31%|███▏      | 40/127 [00:17<00:39,  2.23it/s, loss=3.58, v_num=0]
Epoch 2:  47%|████▋     | 60/127 [00:25<00:29,  2.31it/s, loss=3.58, v_num=0]
Epoch 2:  47%|████▋     | 60/127 [00:26<00:29,  2.31it/s, loss=3.42, v_num=0]
Epoch 2:  63%|██████▎   | 80/127 [00:34<00:20,  2.35it/s, loss=3.42, v_num=0]
Epoch 2:  63%|██████▎   | 80/127 [00:34<00:20,  2.35it/s, loss=3.39, v_num=0]
Epoch 2:  79%|███████▊  | 100/127 [00:42<00:11,  2.38it/s, loss=3.39, v_num=0]
Epoch 2:  79%|███████▊  | 100/127 [00:42<00:11,  2.38it/s, loss=3.43, v_num=0]
Epoch 2:  94%|█████████▍| 120/127 [00:49<00:02,  2.40it/s, loss=3.43, v_num=0]
Epoch 2:  94%|█████████▍| 120/127 [00:50<00:02,  2.40it/s, loss=3.39, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.04it/s]
Epoch 2: 100%|██████████| 127/127 [00:52<00:00,  2.42it/s, loss=3.39, v_num=0]
Epoch 2: 100%|██████████| 127/127 [00:52<00:00,  2.42it/s, loss=3.39, v_num=0]


Epoch 2: 100%|██████████| 127/127 [00:52<00:00,  2.42it/s, loss=3.39, v_num=0]Epoch 2, global step 360: 'val/CER' was not in top 1

Epoch 2:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.39, v_num=0]
Epoch 3:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.39, v_num=0]
Epoch 3:  16%|█▌        | 20/127 [00:08<00:44,  2.42it/s, loss=3.39, v_num=0]
Epoch 3:  16%|█▌        | 20/127 [00:08<00:44,  2.41it/s, loss=3.36, v_num=0]
Epoch 3:  31%|███▏      | 40/127 [00:16<00:35,  2.46it/s, loss=3.36, v_num=0]
Epoch 3:  31%|███▏      | 40/127 [00:16<00:35,  2.45it/s, loss=3.29, v_num=0]
Epoch 3:  47%|████▋     | 60/127 [00:24<00:27,  2.46it/s, loss=3.29, v_num=0]
Epoch 3:  47%|████▋     | 60/127 [00:24<00:27,  2.46it/s, loss=3.25, v_num=0]
Epoch 3:  63%|██████▎   | 80/127 [00:32<00:19,  2.47it/s, loss=3.25, v_num=0]
Epoch 3:  63%|██████▎   | 80/127 [00:32<00:19,  2.47it/s, loss=3.32, v_num=0]
Epoch 3:  79%|███████▊  | 100/127 [00:40<00:10,  2.48it/s, loss=3.32, v_num=0]
Epoch 3:  79%|███████▊  | 100/127 [00:40<00:10,  2.48it/s, loss=3.27, v_num=0]
Epoch 3:  94%|█████████▍| 120/127 [00:48<00:02,  2.49it/s, loss=3.27, v_num=0]
Epoch 3:  94%|█████████▍| 120/127 [00:48<00:02,  2.49it/s, loss=3.25, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.06it/s]
Epoch 3: 100%|██████████| 127/127 [00:50<00:00,  2.51it/s, loss=3.25, v_num=0]
Epoch 3: 100%|██████████| 127/127 [00:50<00:00,  2.51it/s, loss=3.25, v_num=0]


Epoch 3: 100%|██████████| 127/127 [00:50<00:00,  2.51it/s, loss=3.25, v_num=0]Epoch 3, global step 480: 'val/CER' was not in top 1

Epoch 3:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.25, v_num=0]
Epoch 4:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.25, v_num=0]
Epoch 4:  16%|█▌        | 20/127 [00:08<00:43,  2.44it/s, loss=3.25, v_num=0]
Epoch 4:  16%|█▌        | 20/127 [00:08<00:44,  2.43it/s, loss=3.19, v_num=0]
Epoch 4:  31%|███▏      | 40/127 [00:16<00:35,  2.46it/s, loss=3.19, v_num=0]
Epoch 4:  31%|███▏      | 40/127 [00:16<00:35,  2.46it/s, loss=3.19, v_num=0]
Epoch 4:  47%|████▋     | 60/127 [00:24<00:27,  2.48it/s, loss=3.19, v_num=0]
Epoch 4:  47%|████▋     | 60/127 [00:24<00:27,  2.48it/s, loss=3.19, v_num=0]
Epoch 4:  63%|██████▎   | 80/127 [00:32<00:18,  2.49it/s, loss=3.19, v_num=0]
Epoch 4:  63%|██████▎   | 80/127 [00:32<00:18,  2.49it/s, loss=3.29, v_num=0]
Epoch 4:  79%|███████▊  | 100/127 [00:40<00:10,  2.49it/s, loss=3.29, v_num=0]
Epoch 4:  79%|███████▊  | 100/127 [00:40<00:10,  2.49it/s, loss=3.2, v_num=0]
Epoch 4:  94%|█████████▍| 120/127 [00:47<00:02,  2.51it/s, loss=3.2, v_num=0]
Epoch 4:  94%|█████████▍| 120/127 [00:47<00:02,  2.50it/s, loss=3.23, v_num=0]

Validation: 0it [00:00, ?it/s]

Validation:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0:   0%|          | 0/7 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████| 7/7 [00:01<00:00,  4.11it/s]
Epoch 4: 100%|██████████| 127/127 [00:50<00:00,  2.52it/s, loss=3.23, v_num=0]
Epoch 4: 100%|██████████| 127/127 [00:50<00:00,  2.52it/s, loss=3.23, v_num=0]


Epoch 4: 100%|██████████| 127/127 [00:50<00:00,  2.52it/s, loss=3.23, v_num=0]Epoch 4, global step 600: 'val/CER' was not in top 1

Epoch 4:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.23, v_num=0]
Epoch 5:   0%|          | 0/127 [00:00<?, ?it/s, loss=3.23, v_num=0]
Epoch 5:  16%|█▌        | 20/127 [00:08<00:43,  2.44it/s, loss=3.23, v_num=0]
Epoch 5:  16%|█▌        | 20/127 [00:08<00:43,  2.44it/s, loss=3.12, v_num=0]
Epoch 5:  31%|███▏      | 40/127 [00:17<00:37,  2.31it/s, loss=3.12, v_num=0]
Epoch 5:  31%|███▏      | 40/127 [00:17<00:37,  2.31it/s, loss=3.13, v_num=0]
Epoch 5:  47%|████▋     | 60/127 [00:25<00:27,  2.39it/s, loss=3.13, v_num=0]
Epoch 5:  47%|████▋     | 60/127 [00:25<00:28,  2.39it/s, loss=3.22, v_num=0]
Epoch 5:  63%|██████▎   | 80/127 [00:32<00:19,  2.43it/s, loss=3.22, v_num=0]
Epoch 5:  63%|██████▎   | 80/127 [00:32<00:19,  2.43it/s, loss=3.1, v_num=0]
Epoch 5:  79%|███████▊  | 100/127 [00:40<00:10,  2.46it/s, loss=3.1, v_num=0]
Epoch 5:  79%|███████▊  | 100/127 [00:40<00:11,  2.45it/s, loss=3.11, v_num=0]
Epoch 5:  94%|█████████▍| 120/127 [00:48<00:02,  2.47it/s, loss=3.11, v_num=0]
Epoch 5:  94%|█████████▍| 120/127 [00:48<00:02,  2.46it/s, loss=3.08, v_num=0]


,channels,selected_channels,in_features,best_val_CER,final_val_CER,final_test_CER
0,16,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",528,17.34604,17.346035,19.250757
1,12,"[0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14]",396,19.60567,19.605671,21.004765
2,8,"[0, 2, 4, 6, 8, 10, 12, 14]",264,20.04874,20.048737,22.867043
3,4,"[0, 4, 8, 12]",132,26.56181,26.561808,27.479429

Saved summary to:
/content/drive/MyDrive/ECE_C247A_Final_Project/channel_ablation_results.csv

,channels,selected_channels,in_features,best_val_CER,final_val_CER,final_test_CER
0,16,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",528,17.34604,17.346035,19.250757
1,12,"[0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14]",396,19.60567,19.605671,21.004765
2,8,"[0, 2, 4, 6, 8, 10, 12, 14]",264,20.04874,20.048737,22.867043
3,4,"[0, 4, 8, 12]",132,26.56181,26.561808,27.479429

In [ ]:
from google.colab import runtime
runtime.unassign()